### ISSUE TITLE
Dynamic parameters for gravity_compensation

### ISSUE THREAD

**Issue by Schwimo** [Duatic/dynaarm_driver#14]
@firesurfer 

When having this as our gravity_compensation_controller_parameters.yaml, then we must set the command and state interfaces in the controllers.yaml or? But for gravity_compensation this is not needed because we only need the joints parameter to be set?

```
gravity_compensation_controller:
  joints:
    type: string_array
    default_value: []
    description: "Names of joints used by the controller"
    validation:
      unique<>: null
  command_interfaces:
    type: string_array
    description: "Name of the command interface to claim"
    validation:
      size_gt<>: [0]
      unique<>: null
      subset_of<>: [["effort"]]
  state_interfaces:
    type: string_array
    description: "Name of the state interface to claim"
    validation:
      size_gt<>: [0]
      unique<>: null
      subset_of<>: [["position", "velocity"]]
  gains:
    __map_joints:
      p:
        type: double
        default_value: 50.0
        description: "proportional gain term"
        validation:
          gt_eq<>: [ 0.0 ]
      i:
        type: double
        default_value: 0.0
        description: "integral gain term"
        validation:
          gt_eq<>: [ 0.0 ]
      d:
        type: double
        default_value: 15.0
        description: "derivative gain term"
        validation:
          gt_eq<>: [ 0.0 ]
  arm_name:
    type: string
    default_value: "dynaarm"
    description: "name of the arm hardware interface"
```
